language: node_js

sudo: false

node_js:
  - 11.10.1

install: 
  - yarn install
  - yarn run vscode:prepublish

script:
  - npm test --silent

after_success:
  - bash <(curl -s https://codecov.io/bash)
